policies:
  - type: conventionalCommit
    spec:
      types:
        - "chore"
        - "docs"
        - "feat"
        - "fix"
        - "refactor"
        - "style"
        - "test"
      scopes:
        - "*"
